name = "critteria-game-server"
main = "server/index.js"

compatibility_date = "2024-01-13"

[[durable_objects.bindings]]
name = "SERVER_OBJECT"
class_name = "ServerDurableObject"

[[migrations]]
tag = "v1" # Should be unique for each entry
new_classes = ["ServerDurableObject"]
